### ISSUE TITLE
Unable to install in Ubuntu Zesty (17.04)

### ISSUE THREAD

**Issue by ibtehaz-shawon** [haiwen/seafile-user-manual#18]
E: Failed to fetch http://ppa.launchpad.net/seafile/seafile-client/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Please add the package for zesty

**Comment by JanoschDeurer** [comment]
Are there any alternatives? Can we install the client manually?

**Comment by beda42** [comment]
+1 I would also like to see a build for 17.04

**Comment by beda42** [comment]
BTW, you can use the build for 16.10 - it works for me on Ubuntu Mate 17.04.

Just edit the '/etc/apt/sources.list.d/seafile-ubuntu-seafile-client-zesty.list/' and replace 'zesty' with 'yakkety', do 'apt update' and 'apt install seafile-gui' as normal.

It is not a clean solution, but it works.

**Comment by olastor** [comment]
+1 Would be great to keep the client up to date.

**Comment by ibtehaz-shawon** [comment]
@beda42 great. Will do. Thanks.
