### ISSUE TITLE
Where is the "official webpage" I can download the sync client for Linux from?

### ISSUE THREAD

**Issue by thomiel** [haiwen/seafile-user-manual#83]
In en/syncing_client/install_linux_client.md one can read 

`You can download Seafile-x86_64.AppImage from our official website and give it executable permissionns from the teiminal.`

Apart from spelling (it's called a `terminal`), where the heck is your "official website"? There is something called "link" in the internet. Please make use of it!

Why make the experience so cumbersome? In the moment, from the official website I'm being sent to the docs and from there to the official website in a merry-go-round. To me it leaves the impression that you don't want Linux users to use the client any more.

**Comment by thomiel** [comment]
Finally figured it out today:

It seemed to me as if "9.0.7 Please follow this document" was a single link and I always clicked on "Please follow ...". 

Could you make it obvious that these are two separate links, i.e. "Download AppImage 9.0.7" and "Instructions to install the AppImage". Or only just make "this" a hyperlink.

**Comment by killing** [comment]
Thanks for the suggestions. The web pages has been improved.
