### ISSUE TITLE
AppImage installation instruction not precise

### ISSUE THREAD

**Issue by thomiel** [haiwen/seafile-user-manual#84]
The name _Seafile-x86_64.AppImage_ is missing the version number everywhere in the [Linux installation document](https://help.seafile.com/syncing_client/install_linux_client/) and should read _Seafile-x86_64-9.0.7.AppImage_.

The sudo before `chown` [here](https://github.com/haiwen/seafile-user-manual/blob/52c4e625bb2f5234400f43dd7599500efc32351d/en/syncing_client/install_linux_client.md?plain=1#L10C1-L10C38) is not necessary.

**Comment by killing** [comment]
Thanks for suggestion. We'll improve it.
